main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('skaters/', views.skater_index, name='skater-index'),
    path('skaters/<int:skater_id>/', views.skater_detail, name='skater-detail'),
    path('skaters/create/', views.SkaterCreate.as_view(), name='skater-create'),
    path('skaters/<int:pk>/update/', views.SkaterUpdate.as_view(), name='skater-update'),
    path('skaters/<int:pk>/delete/', views.SkaterDelete.as_view(), name='skater-delete'),
    path(
        'skater/<int:skater_id>/add-behavior/', 
        views.add_behavior, 
        name='add-behavior'
    ),
    path('tricks/create/', views.TrickCreate.as_view(), name='trick-create'),
    path('tricks/<int:pk>/', views.TrickDetail.as_view(), name='trick-detail'),
    path('tricks/', views.TrickList.as_view(), name='trick-index'),
    path('tricks/<int:pk>/update/', views.TrickUpdate.as_view(), name='trick-update'),
    path('tricks/<int:pk>/delete/', views.TrickDelete.as_view(), name='trick-delete'), 
    path('skaters/<int:skater_id>/associate-trick/<int:trick_id>/', views.associate_trick, name='associate-trick'),
    path('skater/<int:skater_id>/remove-trick/<int:trick_id>/', views.remove_trick, name='remove-trick'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
]

skatetricks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
BEHAVIORS = (
    ('S', 'Skating'),
    ('L', 'Lewd'),
    ('O', 'Offensive')
)

class Trick(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trick-detail', kwargs={'pk': self.id})

class Skater(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    tricks = models.ManyToManyField(Trick)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    # Define a method to get the URL for this particular cat instance
    def get_absolute_url(self):
        # Use the 'reverse' function to dynamically find the URL for viewing this cat's details
        return reverse('skater-detail', kwargs={'skater_id': self.id})

class Behavior(models.Model):
    date = models.DateField('Behavior Date')
    behavior = models.CharField(
        max_length=1,
        choices=BEHAVIORS,
        default=BEHAVIORS[0][0]
    )
    skater = models.ForeignKey(Skater, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_behavior_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django import forms
from .models import Behavior

class BehaviorForm(forms.ModelForm):
    class Meta:
        model = Behavior
        fields = ['date', 'behavior']
        widgets = {
            'date': forms.DateInput(
            format=('%Y-%m-%d'),
            attrs={
                'placeholder': 'Select a date',
                'type': 'date'
            }
          ),
        }

main_app/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Skater, Trick
from .forms import BehaviorForm
from django.contrib.auth.views import LoginView


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def skater_index(request):
    skaters = Skater.objects.filter(user=request.user)
    return render(request, 'skaters/index.html', {'skaters': skaters})

# views.py
@login_required
def skater_detail(request, skater_id):
    skater = Skater.objects.get(id=skater_id)
    tricks_skater_doesnt_have = Trick.objects.exclude(id__in = skater.tricks.all().values_list('id'))
    behavior_form = BehaviorForm()
    return render(request, 'skaters/detail.html', {
        # include the cat and feeding_form in the context
        'skater': skater, 
        'behavior_form': behavior_form,
        'tricks': tricks_skater_doesnt_have
    })

@login_required
def add_behavior(request, skater_id):
    # create a ModelForm instance using the data in request.POST
    form = BehaviorForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the cat_id assigned
        new_behavior = form.save(commit=False)
        new_behavior.skater_id = skater_id
        new_behavior.save()
    return redirect('skater-detail', skater_id=skater_id)

@login_required
def associate_trick(request, skater_id, trick_id):
    # Note that you can pass a toy's id instead of the whole object
    Skater.objects.get(id=skater_id).tricks.add(trick_id)
    return redirect('skater-detail', skater_id=skater_id)

@login_required
def remove_trick(request, skater_id, trick_id):
    skater = Skater.objects.get(id=skater_id)
    trick = Trick.objects.get(id=trick_id)
    skater.tricks.remove(trick)
    return redirect('skater-detail', skater_id=skater.id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('skater-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )


class Home(LoginView):
    template_name = 'home.html'



class SkaterCreate(LoginRequiredMixin, CreateView):
    model = Skater
    fields = ['name', 'breed', 'description', 'age']
    success_url = '/skaters'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class SkaterUpdate(LoginRequiredMixin, UpdateView):
    model = Skater
    # Let's disallow the renaming of a cat by excluding the name field!
    fields = ['breed', 'description', 'age']

class SkaterDelete(LoginRequiredMixin, DeleteView):
    model = Skater
    success_url = '/skaters/'


class TrickCreate(LoginRequiredMixin, CreateView):
    model = Trick
    fields = ['name', 'breed', 'description', 'age']
    success_url = '/skater'

class TrickList(LoginRequiredMixin, ListView):
    model = Trick

class TrickDetail(LoginRequiredMixin, DetailView):
    model = Trick

class TrickUpdate(LoginRequiredMixin, UpdateView):
    model = Trick
    fields = ['name', 'type']

class TrickDelete(LoginRequiredMixin, DeleteView):
    model = Trick
    success_url = '/tricks/'

main_app/templates/Skaters/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/skaters/skater-detail.css' %}" />
{% endblock %} 
{% block content %}
 <section class="skater-container">
  <div class="skater-img">
    <img src="{% static 'images/Skate Tricks/shrek.png' %}" alt="Shrek stanced up" />
  </div>
  <div class="skater-details">
    <h1>{{ skater.name }}</h1>
    {% if skater.age > 0 %}
      <h2>A {{ skater.age }} year old {{ skater.breed }}</h2>
    {% else %}
      <h2>A {{ skater.breed }} shredder.</h2>
    {% endif %}
    <p>{{ skater.description }}</p>
    <div class="skater-actions">
        <a href="{% url 'skater-update' skater.id %}" class="btn warn">Edit</a>
        <a href="{% url 'skater-delete' skater.id %}" class="btn danger">Delete</a>
      </div>
  </div>
 </section>
 <div class="behaviors-trick-container">
    <section class="behaviors">
      <div class="subsection-title">
        <h2>Behaviors</h2>
        <img
          src="{% static 'images/Skate Tricks/PngItem_98504.png' %}"
          alt="Lil cutout guy skating"
        />
        <img src="{% static 'images/Skate Tricks/PngItem_3439618.png' %}" alt="A cutout skating" />
        <img
          src="{% static 'images/Skate Tricks/PngItem_98871.png' %}"
          alt="Lil cutout guy skating"
        />
      </div>
      <h3>Add a Behavior</h3>
         <form 
            action="{% url 'add-behavior' skater.id %}"
            method="post" 
            class="subsection-content" 
            autocomplete="off"
        >
           {% csrf_token %} 
           {{ behavior_form.as_p }}
           <button type="submit" class="btn submit">Add Behavior</button>
         </form>
         <h3>Past Behaviors</h3>
         {% if skater.behavior_set.all.count %}
           <table>
             <thead>
               <tr>
                 <th>Date</th>
                 <th>Behavior</th>
               </tr>
             </thead>
             <tbody>
               {% for behavior in skater.behavior_set.all %}
               <tr>
                 <td>{{behavior.date}}</td>
                 <td>{{behavior.get_behavior_display}}</td>
               </tr>
               {% endfor %}
             </tbody>
           </table>
         {% else %}
           <div class="subsection-content">
             <p>⚠️ {{skater.name}} has not been acting up!</p>
           </div>
         {% endif %}
        </tbody>
      </table>
    </section>
    <section class="behaviors">
        <!-- This is a long section -->
      </section>
      
      <section class="tricks">
        <div class="subsection-title">
          <h2>Tricks</h2>
          <img src="{% static 'images/Skate Tricks/PngItem_98504.png' %}" alt="A coutout of a guy doing a trick" />
          <img src="{% static 'images/Skate Tricks/PngItem_98871.png' %}" alt="A coutout of a guy doing a trick" />
          <img src="{% static 'images/Skate Tricks/PngItem_3439618.png' %}" alt="A coutout of a guy doing a trick" />
        </div>
        <h3>{{ skater.name }}'s Tricks</h3>
        <div class="subsection-content">
          {% if skater.tricks.count %} 
            {% for trick in skater.tricks.all %}
              <div class="trick-container">
                <div class="color-block" style="background-color: {{ trick.type }}"></div>
                <a href="{% url 'trick-detail' trick.id %}">
                  <p>A {{ trick.type }} {{ trick.name }}</p>
                </a>
                <form action="{% url 'remove-trick' skater.id trick.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove Trick</button>
                  </form>
                  
              </div>
            {% endfor %} 
          {% else %}
            <p class="no-tricks">{{skater.name}} doesn't have any trick! Whack!</p>
          {% endif %}
        </div>

        <h3>Available Tricks</h3>
          <div class="subsection-content">
           {% if tricks.count %} 
            {% for trick in tricks.all %}
             <div class="trick-container">
              <div class="color-block" style="background-color: {{ trick.type }}"></div>
              <a href="{% url 'trick-detail' trick.id %}">
               <p>A {{ trick.type }} {{ trick.name }}</p>
              </a>
              <form action="{% url 'associate-trick' skater.id trick.id %}" method="post">
                {% csrf_token %}
               <button type="submit" class="btn submit">Give trick</button>
              </form>
          </div>
        {% endfor %} 
       {% else %}
          <p class="all-tricks">{{skater.name}} already has all the available trick 🥳 Yeah Boiiii</p>
       {% endif %}
</div>

      </section>
  </div>
  
{% endblock %}

main_app/templates/Skaters/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/skaters/skater-index.css' %}"/>
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>Skater's List</h1>
  <img src="{% static 'images/Skate Tricks/bam-margera.png' %}" alt="Bam Margera" />
  <img src="{% static 'images/Skate Tricks/bigfoot.png' %}" alt="Big Foot" />
  <img src="{% static 'images/Skate Tricks/Shrek.png' %}" alt="Shrek" />
  <img src="{% static 'images/Skate Tricks/tony-hawk.png' %}" alt="Tony Hawk" />
</section>

<section class="card-container">
  {% for skater in skaters %}
    <div class="card">
      <a href="{% url 'skater-detail' skater.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img
            src="{% static 'images/Skate Tricks/shrek.png' %}"
            alt="Shrek"
          />
        </div>
        <h2 class="card-title">{{ skater.name }}</h2>
        {% if skater.age > 0 %}
        <p>A {{ skater.age }} year old {{ skater.breed }}</p>
        {% else %}
        <p>A {{ skater.breed }} skater.</p>
        {% endif %}
        <p><small>{{ skater.description }}</small></p>
      </div>
     </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About Skate Tricks</h1>
<hr />
<p class="page-content">
  I like long romantic walks down the produce aisle. Also, I am currently job
  seeking!
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/Skate Tricks/eye logo.jpg' %}"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <title>Cat Collector</title>
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img src="{% static 'images/Skate Tricks/Skate-Tricks-7-27-2024.png' %}" alt="Skate Tricks Logo" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'skater-index' %}">All Skaters</a></li>
          <li><a href="{% url 'trick-index' %}">All Tricks</a></li>
          <li><a href="{% url 'skater-create' %}">Add a Skater</a></li>
          <li><a href="{% url 'trick-create' %}">Add a Trick</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
              {% csrf_token %}
              <button type="submit">Log out</button>
            </form>
          </li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
    {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<section class="logo-container">
  <div class="skater-container">
    <img src="{% static 'images/Skate Tricks/eye logo.jpg' %}" alt="The Neversoft Eye" />
  </div>
  <img src="{% static 'images/Skate Tricks/Skate-Tricks logotype.png' %}" alt="Text reads: Skate Tricks" />
</section>
{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}

{% endblock %}

main_app/templates/main_app/skater_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Skater?</h1>
  <img src="{% static 'images/Skate Tricks/wee-man.png' %}" alt="Wee Man" />
</div>

<h2>Are you sure you want to delete {{ skater.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'skater-detail' skater.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/skater_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
    {% if skater %}
      <h1>Edit {{ skater.name }}</h1>
    {% else %} 
      <h1>Add a Skater</h1>
    {% endif %}
    <img src="{% static 'images/Skate Tricks/wee-man.png' %}" alt="wee man from jackass" />
  </div>
  
  <form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

main_app/templates/main_app/trick_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Trick?</h1>
  <img src="{% static 'images/Skate Tricks/eye logo.jpg' %}" alt="the neversoft eye logo" />
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'trick-detail' trick.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/trick_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/tricks/trick-detail.css' %}" />
{% endblock %} 
{% block content %}

<div class="card" style="border-color: {{ trick.type }}">
  <div class="card-bg" style="background-color: {{ trick.type }}"></div>
  <div class="card-content">
    <h2>{{ trick.name }}</h2>
    <p>A {{ trick.type }} </p>
  </div>
</div>
<a href="{% url 'trick-update' trick.id %}" class="btn warn">Edit</a>
<a href="{% url 'trick-delete' trick.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/trick_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add a Trick</h1>
    {% endif %}
    <img src="{% static 'images/Skate Tricks/devil.png' %}" alt="A devil" />
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

main_app/templates/main_app/trick_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/tricks/trick-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Skater's Tricks</h1>
  <img src="{% static 'images/Skate Tricks/image 1.jpg' %}" alt="A coutout of a guy doing a trick" />
  <img src="{% static 'images/Skate Tricks/PngItem_98504.png' %}" alt="A coutout of a guy doing a trick" />
  <img src="{% static 'images/Skate Tricks/PngItem_98871.png' %}" alt="A coutout of a guy doing a trick" />
  <img src="{% static 'images/Skate Tricks/PngItem_3439618.png' %}" alt="A coutout of a guy doing a trick" />
</section>

<section class="card-container">
  {% for trick in trick_list %}
    <div class="card" style="border-color: {{ trick.type }}">
      <div class="card-bg" style="background-color: {{ trick.type }}"></div>
      <a href="{% url 'trick-detail' trick.id %}">
        <div class="card-content">
          <h2>{{ trick.name }}</h2>
          <p>A {{ trick.type }} </p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/Skate Tricks/Steve-o.png' %}" alt="It's lovable MTV's Jackass Steve-O!" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}